/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidoFinalizadoRouteImport } from './routes/pedido-finalizado'
import { Route as HistoricoRouteImport } from './routes/historico'
<<<<<<< HEAD
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ARouteImport } from './routes/a'
import { Route as NovoPedidoIdRouteImport } from './routes/novo-pedido.$id'
import { Route as ClienteIdRouteImport } from './routes/cliente.$id'
=======
import { Route as IndexRouteImport } from './routes/index'
>>>>>>> 6a99d4797d826e5d38990802ff9573a075e2a900

const PedidoFinalizadoRoute = PedidoFinalizadoRouteImport.update({
  id: '/pedido-finalizado',
  path: '/pedido-finalizado',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ARoute = ARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoPedidoIdRoute = NovoPedidoIdRouteImport.update({
  id: '/novo-pedido/$id',
  path: '/novo-pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIdRoute = ClienteIdRouteImport.update({
  id: '/cliente/$id',
  path: '/cliente/$id',
=======
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
>>>>>>> 6a99d4797d826e5d38990802ff9573a075e2a900
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
<<<<<<< HEAD
  '/a': typeof ARoute
  '/checkout': typeof CheckoutRoute
  '/clientes': typeof ClientesRoute
=======
  '/': typeof IndexRoute
>>>>>>> 6a99d4797d826e5d38990802ff9573a075e2a900
  '/historico': typeof HistoricoRoute
  '/pedido-finalizado': typeof PedidoFinalizadoRoute
  '/cliente/$id': typeof ClienteIdRoute
  '/novo-pedido/$id': typeof NovoPedidoIdRoute
}
export interface FileRoutesByTo {
<<<<<<< HEAD
  '/a': typeof ARoute
  '/checkout': typeof CheckoutRoute
  '/clientes': typeof ClientesRoute
=======
  '/': typeof IndexRoute
>>>>>>> 6a99d4797d826e5d38990802ff9573a075e2a900
  '/historico': typeof HistoricoRoute
  '/pedido-finalizado': typeof PedidoFinalizadoRoute
  '/cliente/$id': typeof ClienteIdRoute
  '/novo-pedido/$id': typeof NovoPedidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
<<<<<<< HEAD
  '/a': typeof ARoute
  '/checkout': typeof CheckoutRoute
  '/clientes': typeof ClientesRoute
=======
  '/': typeof IndexRoute
>>>>>>> 6a99d4797d826e5d38990802ff9573a075e2a900
  '/historico': typeof HistoricoRoute
  '/pedido-finalizado': typeof PedidoFinalizadoRoute
  '/cliente/$id': typeof ClienteIdRoute
  '/novo-pedido/$id': typeof NovoPedidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths:
    | '/a'
    | '/checkout'
    | '/clientes'
    | '/historico'
    | '/pedido-finalizado'
    | '/cliente/$id'
    | '/novo-pedido/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/a'
    | '/checkout'
    | '/clientes'
    | '/historico'
    | '/pedido-finalizado'
    | '/cliente/$id'
    | '/novo-pedido/$id'
  id:
    | '__root__'
    | '/a'
    | '/checkout'
    | '/clientes'
    | '/historico'
    | '/pedido-finalizado'
    | '/cliente/$id'
    | '/novo-pedido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ARoute: typeof ARoute
  CheckoutRoute: typeof CheckoutRoute
  ClientesRoute: typeof ClientesRoute
=======
  fullPaths: '/' | '/historico'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historico'
  id: '__root__' | '/' | '/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
>>>>>>> 6a99d4797d826e5d38990802ff9573a075e2a900
  HistoricoRoute: typeof HistoricoRoute
  PedidoFinalizadoRoute: typeof PedidoFinalizadoRoute
  ClienteIdRoute: typeof ClienteIdRoute
  NovoPedidoIdRoute: typeof NovoPedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedido-finalizado': {
      id: '/pedido-finalizado'
      path: '/pedido-finalizado'
      fullPath: '/pedido-finalizado'
      preLoaderRoute: typeof PedidoFinalizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a': {
      id: '/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof ARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-pedido/$id': {
      id: '/novo-pedido/$id'
      path: '/novo-pedido/$id'
      fullPath: '/novo-pedido/$id'
      preLoaderRoute: typeof NovoPedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/$id': {
      id: '/cliente/$id'
      path: '/cliente/$id'
      fullPath: '/cliente/$id'
      preLoaderRoute: typeof ClienteIdRouteImport
=======
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
>>>>>>> 6a99d4797d826e5d38990802ff9573a075e2a900
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
<<<<<<< HEAD
  ARoute: ARoute,
  CheckoutRoute: CheckoutRoute,
  ClientesRoute: ClientesRoute,
=======
  IndexRoute: IndexRoute,
>>>>>>> 6a99d4797d826e5d38990802ff9573a075e2a900
  HistoricoRoute: HistoricoRoute,
  PedidoFinalizadoRoute: PedidoFinalizadoRoute,
  ClienteIdRoute: ClienteIdRoute,
  NovoPedidoIdRoute: NovoPedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
